### PR TITLE
Added NLog Layout support for NatsUrl and Subject

### PR DESCRIPTION
**Pull request by snakefoot**
NLog Layout allows you to configure NATS-Target options from config-file like `NLog.config` or `appsettings.json`.

Would it be possible to change the license for this project from GPL to Apache (Like NATS) or BSD3 (Like NLog) ?

### CODE REVIEW

**Comment by Siqsuruq** [comment]
I moved project to Apache 2.0 License

**Comment by snakefoot** [comment]
Thank you for the merge, and approving the suggested change of license.

**Comment by Siqsuruq** [comment]
I've updated the version on nuget.org also to 1.0.1, including your commits
and some typo fixes. Thank you.

**Comment by snakefoot** [comment]
Thank you for the quick merges, and the release. I have added the nuget-package to the list of custom NLog Targets here:

- https://nlog-project.org/config/?tab=targets

**Pull request merged**
